import { Dimensions } from "react-native";

const DEVICE_WIDTH = Dimensions.get("window").width;

const DESKTOP_BANNER_GUESS_GRID_MIN_WIDTH = 298;
const DESKTOP_BANNER_GUESS_GRID_MAX_WIDTH = 386;

const MOBILE_BANNER_GUESS_GRID_MIN_WIDTH = 256;
const MOBILE_BANNER_GUESS_GRID_MAX_WIDTH = 332;

const WORD_CARD_MIN_WIDTH = 280;
const WORD_CARD_MAX_WIDTH = 368;

const MIN_BANNER_HEIGHT = 64;

const DESKTOP_MODAL_MAX_WIDTH = 400;
const MOBILE_MODAL_MAX_WIDTH = 600;

const MOBILE_MODAL_MAX_HEIGHT = 600;
const DESKTOP_MODAL_TOP_OFFSET = -200;

export {
  DEVICE_WIDTH,
  DESKTOP_BANNER_GUESS_GRID_MIN_WIDTH,
  DESKTOP_BANNER_GUESS_GRID_MAX_WIDTH,
  MOBILE_BANNER_GUESS_GRID_MIN_WIDTH,
  MOBILE_BANNER_GUESS_GRID_MAX_WIDTH,
  WORD_CARD_MIN_WIDTH,
  WORD_CARD_MAX_WIDTH,
  MIN_BANNER_HEIGHT,
  DESKTOP_MODAL_MAX_WIDTH,
  MOBILE_MODAL_MAX_WIDTH,
  MOBILE_MODAL_MAX_HEIGHT,
  DESKTOP_MODAL_TOP_OFFSET,
};
