import { Dimensions } from "react-native";

const DEVICE_WIDTH = Dimensions.get("window").width;

const BANNER_GUESS_GRID_MIN_WIDTH = 280;
const BANNER_GUESS_GRID_MAX_WIDTH = 324;

const WORD_CARD_MIN_WIDTH = 280;
const WORD_CARD_MAX_WIDTH = 400;

const MIN_BANNER_HEIGHT = 64;

export {
  DEVICE_WIDTH,
  BANNER_GUESS_GRID_MIN_WIDTH,
  BANNER_GUESS_GRID_MAX_WIDTH,
  WORD_CARD_MIN_WIDTH,
  WORD_CARD_MAX_WIDTH,
  MIN_BANNER_HEIGHT,
};
