import { Dimensions } from "react-native";

const DEVICE_WIDTH = Dimensions.get("window").width;

const DESKTOP_BANNER_GUESS_GRID_MIN_WIDTH = 280;
const DESKTOP_BANNER_GUESS_GRID_MAX_WIDTH = 368;

const MOBILE_BANNER_GUESS_GRID_MIN_WIDTH = 240;
const MOBILE_BANNER_GUESS_GRID_MAX_WIDTH = 316;

const WORD_CARD_MIN_WIDTH = 280;
const WORD_CARD_MAX_WIDTH = 368;

const MIN_BANNER_HEIGHT = 64;

export {
  DEVICE_WIDTH,
  DESKTOP_BANNER_GUESS_GRID_MIN_WIDTH,
  DESKTOP_BANNER_GUESS_GRID_MAX_WIDTH,
  MOBILE_BANNER_GUESS_GRID_MIN_WIDTH,
  MOBILE_BANNER_GUESS_GRID_MAX_WIDTH,
  WORD_CARD_MIN_WIDTH,
  WORD_CARD_MAX_WIDTH,
  MIN_BANNER_HEIGHT,
};
