import { WordEntry, WordId } from "@/types/word";

/**
 * Central source of truth for all playable words.
 * TODO: migrate the remaining entries from the old WORDS/HINTS/SUMMARIES constants.
 */
const WORD_DATA: WordEntry[] = [
  { id: "SLATE", category: "common" },
  { id: "TRACE", category: "common" },
  { id: "ROAST", category: "common" },
  { id: "STARE", category: "common" },
  { id: "CARET", category: "common" },
  { id: "CRANE", category: "common" },
  { id: "SLANT", category: "common" },
  { id: "STALE", category: "common" },
  { id: "STOLE", category: "common" },
  { id: "SNARE", category: "common" },
  { id: "IRATE", category: "common" },
  { id: "AROSE", category: "common" },
  { id: "TRAIN", category: "common" },
  { id: "TASER", category: "common" },
  { id: "RAISE", category: "common" },
  { id: "TRADE", category: "common" },
  { id: "ORATE", category: "common" },
  { id: "SLICE", category: "common" },
  { id: "LANCE", category: "common" },
  { id: "STORE", category: "common" },
  { id: "TARES", category: "common" },
  { id: "LEANT", category: "common" },
  { id: "ALTER", category: "common" },
  { id: "CRONE", category: "common" },
  { id: "CLOSE", category: "common" },
  { id: "ARIEL", category: "common" },
  { id: "ARISE", category: "common" },
  { id: "AISLE", category: "common" },
  { id: "SCALE", category: "common" },
  { id: "ALONE", category: "common" },
  { id: "TEARS", category: "common" },
  { id: "SITAR", category: "common" },
  { id: "SNORE", category: "common" },
  { id: "CANST", category: "common" },
  { id: "TAILS", category: "common" },
  { id: "TRIAL", category: "common" },
  { id: "CASTE", category: "common" },
  { id: "PLANE", category: "common" },
  { id: "RESAT", category: "common" },
  { id: "TONER", category: "common" },
  { id: "TRANS", category: "common" },
  { id: "TALES", category: "common" },
  { id: "SCARE", category: "common" },
  { id: "ALERT", category: "common" },
  { id: "CATER", category: "common" },
  { id: "DEALT", category: "common" },
  { id: "EARNT", category: "common" },
  { id: "RINSE", category: "common" },
  { id: "RATES", category: "common" },
  { id: "LEARN", category: "common" },
  { id: "SIREN", category: "common" },
  { id: "TRIES", category: "common" },
  { id: "REALS", category: "common" },
  { id: "STAIR", category: "common" },
  { id: "SALON", category: "common" },
  { id: "CLONE", category: "common" },
  { id: "NITRE", category: "common" },
  { id: "LATER", category: "common" },
  { id: "COAST", category: "common" },
  { id: "CANOE", category: "common" },
  { id: "CAIRN", category: "common" },
  { id: "SNORT", category: "common" },
  { id: "TENOR", category: "common" },
  { id: "CAROL", category: "common" },
  { id: "LITRE", category: "common" },
  { id: "SONAR", category: "common" },
  { id: "PARSE", category: "common" },
  { id: "GRATE", category: "common" },
  { id: "TRODE", category: "common" },
  { id: "CARES", category: "common" },
  { id: "ATONE", category: "common" },
  { id: "TRIPE", category: "common" },
  { id: "SAUTE", category: "common" },
  { id: "CLADE", category: "common" },
  { id: "SCANT", category: "common" },
  { id: "DRONE", category: "common" },
  { id: "TALON", category: "common" },
  { id: "TRUCE", category: "common" },
  { id: "SORTA", category: "common" },
  { id: "SLOAN", category: "common" },
  { id: "CRUET", category: "common" },
  { id: "TRIED", category: "common" },
  { id: "STONE", category: "common" },
  { id: "SPARE", category: "common" },
  { id: "TIRES", category: "common" },
  { id: "CREST", category: "common" },
  { id: "TROPE", category: "common" },
  { id: "NACRE", category: "common" },
  { id: "CLINT", category: "common" },
  { id: "TILES", category: "common" },
  { id: "SATIN", category: "common" },
  { id: "SINCE", category: "common" },
  { id: "LEANS", category: "common" },
  { id: "PEARL", category: "common" },
  { id: "SOLAR", category: "common" },
  { id: "SHARE", category: "common" },
  { id: "SHALE", category: "common" },
  { id: "TROIS", category: "common" },
  { id: "REACT", category: "common" },
  { id: "MISTY", category: "common" },
  { id: "PLAIN", category: "common" },
  { id: "HOIST", category: "common" },
  { id: "PLATE", category: "common" },
  { id: "NOISE", category: "common" },
  {
    id: "PIXAR",
    category: "movies",
    edition: 1,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Pixar",
  },
  {
    id: "NOVEL",
    category: "literature",
    edition: 2,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Novel",
  },
  {
    id: "EMAIL",
    category: "techAndInternetCulture",
    edition: 3,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Email",
  },
  {
    id: "ATOMS",
    category: "science",
    edition: 4,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Atom",
  },
  {
    id: "ZELDA",
    category: "videoGames",
    edition: 5,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/The_Legend_of_Zelda",
  },
  {
    id: "MAGIC",
    category: "fantasyAndSciFi",
    edition: 6,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Magic_(supernatural)",
  },
  {
    id: "JOKER",
    category: "superheroes",
    edition: 7,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Joker_(character)",
  },
  {
    id: "CHESS",
    category: "tabletopAndBoardGames",
    edition: 8,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Chess",
  },
  {
    id: "MANGA",
    category: "animeAndManga",
    edition: 9,
    summary: "",
    hints: [],
    wikipediaUrl: "https://en.wikipedia.org/wiki/Manga",
  },
];

export const getWordEntry = (id: WordId): WordEntry => {
  const entry = WORD_DATA.find((word) => word.id === id);
  if (!entry) {
    throw new Error(`Word not found: ${id}`);
  }
  return entry;
};

export { WORD_DATA };
