#!/usr/bin/env node

/**
 * Development Environment Helper
 * Quick utility to manage .env.local file for different development scenarios
 */

const fs = require("fs");
const path = require("path");

// Get the project root directory
const ENV_FILE = path.join(process.cwd(), ".env.local");

const presets = {
  // Standard local development
  development: {
    EXPO_PUBLIC_DEV_MODE: "true",
    EXPO_PUBLIC_ENABLE_DEBUG_LOGS: "true",
    EXPO_PUBLIC_BYPASS_DAILY_LIMIT: "false",
    EXPO_PUBLIC_SHOW_DEV_BADGE: "true",
    EXPO_PUBLIC_API_URL:
      "http://127.0.0.1:5001/nerd-word-cfda3/us-central1/api",
  },

  // Testing with dev overrides
  testing: {
    EXPO_PUBLIC_DEV_MODE: "true",
    EXPO_PUBLIC_ENABLE_DEBUG_LOGS: "true",
    EXPO_PUBLIC_BYPASS_DAILY_LIMIT: "true",
    EXPO_PUBLIC_SHOW_DEV_BADGE: "true",
    EXPO_PUBLIC_API_URL:
      "http://127.0.0.1:5001/nerd-word-cfda3/us-central1/api",
  },
};

function createEnvFile(preset) {
  const config = presets[preset];
  if (!config) {
    console.error(`❌ Unknown preset: ${preset}`);
    console.error(`Available presets: ${Object.keys(presets).join(", ")}`);
    process.exit(1);
  }

  let content = `# Local development environment variables\n`;
  content += `# Generated by: npm run env:${preset}\n\n`;

  Object.entries(config).forEach(([key, value]) => {
    content += `${key}=${value}\n`;
  });

  content += `\n# Firebase Emulator (auto-detected by SDK)\n`;
  content += `# FIRESTORE_EMULATOR_HOST=localhost:8080\n`;

  fs.writeFileSync(ENV_FILE, content);
  console.log(`✅ Updated .env.local with ${preset} preset`);

  if (preset === "testing") {
    console.log(`🧪 Testing mode: Daily bypass ON, Dev badge ON`);
  } else {
    console.log(`🔧 Development mode: Debug logs ON, No bypass`);
  }
}

function showCurrentConfig() {
  if (!fs.existsSync(ENV_FILE)) {
    console.log(`❌ No .env.local file found`);
    return;
  }

  const content = fs.readFileSync(ENV_FILE, "utf8");
  console.log(`📋 Current .env.local configuration:\n`);
  console.log(content);
}

// Parse command line arguments
const command = process.argv[2];

switch (command) {
  case "development":
  case "testing":
    createEnvFile(command);
    break;
  case "show":
    showCurrentConfig();
    break;
  default:
    console.log(`Development Environment Helper`);
    console.log(`Usage: node scripts/env-helper.js <command>`);
    console.log(``);
    console.log(`Commands:`);
    console.log(`  development  - Standard dev mode`);
    console.log(`  testing      - Testing with bypass enabled`);
    console.log(`  show         - Show current configuration`);
    break;
}
