import * as admin from "firebase-admin";
import { WORD_DATA } from "../../../constants/words";
import { wordEntryToFirestore } from "../utils";

// Initialize Firebase Admin SDK for emulator
if (!admin.apps.length) {
  admin.initializeApp({
    projectId: "nerd-word-cfda3",
  });
}

const db = admin.firestore();

/**
 * PRODUCTION DAILY PUZZLE ALGORITHM
 *
 * This is the real production algorithm that:
 * 1. Starts with edition 1 words after alpha/beta testing is complete
 * 2. Uses intelligent selection based on category diversity, difficulty, etc.
 * 3. Tracks usage stats and avoids repetition
 */

async function seedProductionPuzzles() {
  console.log("🚀 [PRODUCTION] Starting production puzzle algorithm...");

  // Get all nerd words and sort by edition (start with edition 1)
  const productionWords = WORD_DATA.filter(
    (word) => word.category !== "common"
  ).sort((a, b) => {
    const aEdition = (a as any).edition || 0;
    const bEdition = (b as any).edition || 0;
    return aEdition - bEdition; // Start with edition 1
  });

  console.log(`📝 Found ${productionWords.length} words for production`);
  console.log(
    `📊 Starting with edition ${(productionWords[0] as any)?.edition || 1}`
  );

  const selectedWords = productionWords; // Use all 126 words

  const batch = db.batch();
  const startDate = new Date();

  try {
    for (let i = 0; i < selectedWords.length; i++) {
      const puzzleDate = new Date(startDate);
      puzzleDate.setDate(startDate.getDate() + i);
      const dateString = puzzleDate.toISOString().split("T")[0];

      const word = selectedWords[i];
      const puzzleRef = db.collection("dailyPuzzles").doc(dateString);

      batch.set(puzzleRef, {
        word: wordEntryToFirestore(word),
        solveCount: 0,
        averageGuesses: 0,
        createdAt: new Date(),
        isGenerated: true, // Generated by production algorithm
        cycleLap: 1,
        algorithm: "edition-based-v1", // Track which algorithm version
      });
    }

    await batch.commit();
    console.log("✅ Production puzzles seeded successfully!");
    console.log(`📅 Scheduled ${selectedWords.length} production puzzles`);
  } catch (error) {
    console.error("❌ Error seeding production puzzles:", error);
    throw error;
  }
}

async function main() {
  try {
    await seedProductionPuzzles();
    console.log("🏁 Production seeding completed!");
    process.exit(0);
  } catch (error) {
    console.error("💥 Production seeding failed:", error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

export { seedProductionPuzzles };
